debug

diff --git a/.github/workflows/docker-build-push.yml b/.github/workflows/docker-build-push.yml
--- a/.github/workflows/docker-build-push.yml
+++ b/.github/workflows/docker-build-push.yml
@@ -4,8 +4,6 @@ on:
   push:
     tags:
       - 'v*'  # match all v prefix tag
-    branches:
-      - develop  # limit develop branch tag touch
 
 env:
   REGISTRY_NAME: ${{ secrets.REGISTRY }}
@@ -35,22 +33,24 @@ jobs:
           echo "DOCKER_TAG=${TAG_NAME}" >> "$GITHUB_OUTPUT"
           echo "Extracted tag: ${GITHUB_OUTPUT} -- ${TAG_NAME}"
 
-      - name: Login to Azure Container Registry
-        uses: azure/docker-login@v1
-        with:
-          login-server: ${{ secrets.REGISTRY }}
-          username: ${{ secrets.ACR_USERNAME }}
-          password: ${{ secrets.ACR_PASSWORD }}
+      - name: Determine Branch and Image Name
+        id: determine-branch
+        run: |
+          # obtain tag against tag
+          COMMIT=$(git rev-list -n 1 ${{ github.ref }})
+          echo "commit:  ${COMMIT} "
+          BROUT=$(git branch -a --contains $COMMIT)
+          echo "BROUT:  ${BROUT} "
+          RESULT1 = $(git branch -a --contains $COMMIT | grep -Eq '(^|/)develop(/|$)')
+          echo "RESULT1:  $?"
 
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v5
-        with:
-          context: ${{ env.BUILD_CONTEXT }}  # config build context
-          file: ${{ env.DOCKERFILE_PATH }}    # finger out Dockerfile path
-          push: true
-          tags: |
-            ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.extract-tag.outputs.DOCKER_TAG }}
-            ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
-          labels: |
-            org.opencontainers.image.source=${{ github.repositoryUrl }}
-            org.opencontainers.image.version=${{ steps.extract-tag.outputs.DOCKER_TAG }}
+          # check tag belong to which branch
+          if git branch -a --contains $COMMIT | grep -Eq '(^|/)develop(/|$)'; then
+            echo "BRANCH_NAME=develop" >> $GITHUB_OUTPUT
+            echo "IMAGE_NAME=mileage-dev-web-app" >> $GITHUB_OUTPUT
+          else
+            echo "BRANCH_NAME=unknown" >> $GITHUB_OUTPUT
+            echo "::error::Tag is not on develop branch!"
+            exit 1
+          fi
+
